// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_-iqeQVPLQLUKy7DaTOeI0DJW2FVqEnA',
    appId: '1:953080812028:web:cdd1430d4d5af0f719a279',
    messagingSenderId: '953080812028',
    projectId: 'mundifex-4ea8d',
    authDomain: 'mundifex-4ea8d.firebaseapp.com',
    storageBucket: 'mundifex-4ea8d.appspot.com',
    measurementId: 'G-CGYLHDDT5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEZyke3UxW8AlThBryqhoc3tU1zfQmGB8',
    appId: '1:953080812028:android:8994c91f0f78a6ae19a279',
    messagingSenderId: '953080812028',
    projectId: 'mundifex-4ea8d',
    storageBucket: 'mundifex-4ea8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0NvjvW9dw1lljTOHTvJHKAO6YYXGf_4',
    appId: '1:953080812028:ios:16624c1a67781bc919a279',
    messagingSenderId: '953080812028',
    projectId: 'mundifex-4ea8d',
    storageBucket: 'mundifex-4ea8d.appspot.com',
    iosBundleId: 'com.manolaqe.mundifex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu0NvjvW9dw1lljTOHTvJHKAO6YYXGf_4',
    appId: '1:953080812028:ios:16624c1a67781bc919a279',
    messagingSenderId: '953080812028',
    projectId: 'mundifex-4ea8d',
    storageBucket: 'mundifex-4ea8d.appspot.com',
    iosBundleId: 'com.manolaqe.mundifex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_-iqeQVPLQLUKy7DaTOeI0DJW2FVqEnA',
    appId: '1:953080812028:web:6012a550dfecba5919a279',
    messagingSenderId: '953080812028',
    projectId: 'mundifex-4ea8d',
    authDomain: 'mundifex-4ea8d.firebaseapp.com',
    storageBucket: 'mundifex-4ea8d.appspot.com',
    measurementId: 'G-2SE7EPF0C2',
  );
}
